### ISSUE TITLE
Develop a search API for the Thesaurus Concepts

### ISSUE THREAD

**Issue by pasqLisena** [silknow/api#1]
Develop a search API for the Thesaurus Concepts.

Inspiration: http://overture.doremus.org/api/vocabulary/mop?q=piano

**Comment by pasqLisena** [comment]
Do we have here implementation needs?

The best for me would be setting up a NodeJS server for this.

Alternative: separate the component in a JS module (installable with npm) and integrate it in ADAsilk.

**Comment by rtroncy** [comment]
Yes, I believe we do have this need that could increase the usage of the thesaurus, as I believe that it should be part of some best practices to not only provide the thesaurus in a machine readable format (SKOS) but also provide a visualization (e.g. based on SKOSMOS), and a reconciliation API.

+1 for setting up a NodeJS server for this purpose.

**Comment by pasqLisena** [comment]
closed in e431920
